# Generated by Django 5.0.2 on 2024-02-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_product_description_auctionlisting_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
