# Generated by Django 5.0.2 on 2024-02-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlisting_image_auctionlisting_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('imageUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='auctions.category'),
        ),
    ]
