# Generated by Django 5.0.2 on 2024-02-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_category_auctionlisting_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
