# Generated by Django 5.0.2 on 2024-02-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_category_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
