# Generated by Django 5.0.2 on 2024-02-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_auctionlisting_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='categories',
            new_name='category',
        ),
    ]
