# Generated by Django 5.0.2 on 2024-02-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auctionlisting_numberofbids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='numberOfBids',
            field=models.IntegerField(),
        ),
    ]
